export enum CurrencyType {
    AUD = "AUD",
    USD = "USD",
    EUR = "EUR",
    GBP = "GBP"
}

export enum Categories {
    "ATP 250" = "ATP 250",
    "ATP 500" = "ATP 500",
    "ATP Masters 1000" = "ATP Masters 1000",
    "Grand Slam" = "Grand Slam",
    "ATP Finals" = "ATP Finals",
    "ATP Cup" = "ATP Cup",
    ILTF = "ILTF",
    ITF = "ITF",
    "Laver Cup" = "Laver Cup",
    "Next Gen Finals" = "Next Gen Finals",
    NTL = "NTL",
    Olympics = "Olympics",
    United = "United",
    "Davis Cup" = "Davis Cup",
    "Grand Prix" = "Grand Prix"
}

export enum Surfaces {
    Hard = "Hard",
    Clay = "Clay",
    Grass = "Grass",
    Carpet = "Carpet",
    "Outdoor Hard (Greenset)" = "Outdoor Hard (Greenset)",
    "Outdoor Hard (Plexipave)" = "Outdoor Hard (Plexipave)",
    "Outdoor Hard (Laykold)" = "Outdoor Hard (Laykold)",
    "Indoor Hard (Greenset)" = "Indoor Hard (Greenset)",
    "Outdoor Hard (Solflex)" = "Outdoor Hard (Solflex)",
    "Outdoor Hard (Decoturf)" = "Outdoor Hard (Decoturf)",
    "Indoor Hard (Plexicushion)" = "Indoor Hard (Plexicushion)",
    "Indoor Hard (Proflex)" = "Indoor Hard (Proflex)",
    "Indoor Hard (Acrylic)" = "Indoor Hard (Acrylic)",
    "Outdoor Hard (Plexicushion)" = "Outdoor Hard (Plexicushion)",
    "Outdoor Hard (Sport Master)" = "Outdoor Hard (Sport Master)",
    "Indoor Hard (Plexipave)" = "Indoor Hard (Plexipave)",
    "Indoor Hard (Rebound ace)" = "Indoor Hard (Rebound ace)",
    "Indoor Hard (Slamcourt)" = "Indoor Hard (Slamcourt)",
    "Indoor Hard (Gerflor)" = "Indoor Hard (Gerflor)",
    "Outdoor Hard (Court Master)" = "Outdoor Hard (Court Master)",
    "Indoor Hard (Decoturf)" = "Indoor Hard (Decoturf)", "Outdoor Hard (Rebound ace)" = "Outdoor Hard (Rebound ace)",
    "Indoor Hard (Laykold)" = "Indoor Hard (Laykold)",
    "Outdoor Clay" = "Outdoor Clay",
    "Outdoor Hard" = "Outdoor Hard",
    "Indoor Hard" = "Indoor Hard",
    "Outdoor Grass" = "Outdoor Grass",
    "Outdoor Hard (Har-Tru)" = "Outdoor Hard (Har-Tru)",
    "Indoor Hard (TP Surface)" = "Indoor Hard (TP Surface)",
    "Indoor Carpet" = "Indoor Carpet",
    "Outdoor Hard (Play pave)" = "Outdoor Hard (Play pave)",
    Various = "Various",
    "Indoor Clay" = "Indoor Clay",
    "Indoor Hard (Premier)" = "Indoor Hard (Premier)",
    "Indoor Hard (PlayIt)" = "Indoor Hard (PlayIt)"
}

export enum MonthNames {
    January = "January",
    February = "February",
    March = "March",
    April = "April",
    May = "May",
    June = "June",
    July = "July",
    August = "August",
    September = "September",
    October = "October",
    November = "November",
    December = "December"
}

export enum MonthNumbers {
    January = 1,
    February = 2,
    March = 3,
    April = 4,
    May = 5,
    June = 6,
    July = 7,
    August = 8,
    September = 9,
    October = 10,
    November = 11,
    December = 12
}

export enum StatusType {
    LL = "LL",
    PR = "PR",
    WC = "WC",
    SE = "SE",
    Q = "Q",
    Alt = "Alt"
}

export enum ShortRoundsType {
    "Round of 128" = "Round of 128",
    "Round of 64" = "Round of 64",
    "Round of 32" = "Round of 32",
    "Round of 16" = "Round of 16",
    "Quarterfinals" = "Quarterfinals",
    "Semifinals" = "Semifinals",
    "Final" = "Final"
}

export enum SearchResultKeysEnum {
    PLAYERS = "Players",
    TOURNAMENTS = "Tournaments",
    COUNTRIES = "Countries",
    VENUES = "Venues",
    SURFACES = "Surfaces",
    COACHES = "Coaches",
    UMPIRES = "Umpires",
    SUPERVISORS = "Supervisors"
}

export enum Countries {
    ARG = "ARG",
    ARM = "ARM",
    AUS = "AUS",
    AUT = "AUT",
    BEL = "BEL",
    BFA = "BFA",
    BGD = "BGD",
    BGR = "BGR",
    BIH = "BIH",
    BOL = "BOL",
    BRA = "BRA",
    BRB = "BRB",
    BHR = "BHR",
    CAN = "CAN",
    CHI = "CHI",
    CHN = "CHN",
    COL = "COL",
    CRO = "CRO",
    CYP = "CYP",
    CZE = "CZE",
    DEN = "DEN",
    DMA = "DMA",
    DOM = "DOM",
    ECU = "ECU",
    EGY = "EGY",
    ESP = "ESP",
    EST = "EST",
    FIN = "FIN",
    FRA = "FRA",
    GBR = "GBR",
    GEO = "GEO",
    GER = "GER",
    HKG = "HKG",
    HUN = "HUN",
    IND = "IND",
    IRL = "IRL",
    ISR = "ISR",
    ITA = "ITA",
    JAM = "JAM",
    JOR = "JOR",
    JPN = "JPN",
    KAZ = "KAZ",
    KSA = "KSA",
    LBN = "LBN",
    LTU = "LTU",
    LUX = "LUX",
    MAR = "MAR",
    MDA = "MDA",
    MEX = "MEX",
    MON = "MON",
    NED = "NED",
    NOR = "NOR",
    NZL = "NZL",
    PAK = "PAK",
    PAN = "PAN",
    PER = "PER",
    POL = "POL",
    POR = "POR",
    QAT = "QAT",
    ROU = "ROU",
    RUS = "RUS",
    SRB = "SRB",
    SUI = "SUI",
    SVK = "SVK",
    SWE = "SWE",
    THA = "THA",
    TUN = "TUN",
    TUR = "TUR",
    UAE = "UAE",
    UKR = "UKR",
    USA = "USA",
    UZB = "UZB",
    VEN = "VEN"
}
