export default defineAppConfig({
  ui: {
    colors: {
      primary: "sky",
      success: "green",
      warning: "amber",
      error: "red",
      ATP: "indigo",
      WTA: "fuchsia",
      Men: "blue",
      Women: "pink",
      Active: "emerald",
      Inactive: "zinc",
      Singles: "violet",
      Doubles: "orange",
      Tour: "teal",
      Challenger: "stone",
      ITF: "rose",
      Main: "lime",
      Qualifying: "gray"
    },
    icons: {
      arrowLeft: "line-md:arrow-left-circle-twotone",
      arrowRight: "line-md:arrow-right-circle-twotone",
      caution: "line-md:alert-circle-twotone-loop",
      check: "line-md:square-twotone-to-confirm-square-twotone-transition",
      chevronDoubleLeft: "line-md:chevron-small-double-left",
      chevronDoubleRight: "line-md:chevron-small-double-right",
      chevronDown: "line-md:chevron-small-down",
      chevronLeft: "line-md:chevron-small-left",
      chevronRight: "line-md:chevron-small-right",
      chevronUp: "line-md:chevron-small-up",
      close: "line-md:close-circle-twotone",
      copy: "solar:copy-bold-duotone",
      copyCheck: "tabler:copy-check",
      dark: "line-md:moon-rising-twotone-alt-loop",
      ellipsis: "tabler:dots-circle-horizontal",
      error: "line-md:close-circle-twotone",
      external: "line-md:external-link-rounded",
      eye: "line-md:watch-twotone",
      eyeOff: "line-md:watch-off-twotone",
      file: "line-md:file-document-twotone",
      folder: "tabler:folder",
      folderOpen: "tabler:folder-open",
      hash: "line-md:hash-small",
      info: "solar:info-circle-bold-duotone",
      light: "line-md:sun-rising-twotone-loop",
      loading: "line-md:loading-twotone-loop",
      menu: "solar:hamburger-menu-line-duotone",
      minus: "line-md:minus",
      panelClose: "tabler:layout-sidebar-left-collapse",
      panelOpen: "tabler:layout-sidebar-left-expand",
      plus: "line-md:plus",
      search: "line-md:search-twotone",
      success: "line-md:circle-to-confirm-circle-twotone-transition",
      system: "line-md:monitor-twotone",
      tip: "line-md:lightbulb-twotone",
      warning: "line-md:alert-twotone-loop"
    },
    button: {
      slots: { base: "cursor-pointer" },
      defaultVariants: { variant: "subtle", size: "sm" }
    },
    commandPalette: { slots: { input: "[&>input]:h-8 text-xs", item: "cursor-pointer text-sm" } },
    dashboardSidebar: { slots: { header: "justify-center font-cursive lg:text-lg xl:text-xl 2xl:text-2xl" } },
    footerColumns: { slots: { center: "xl:col-span-3" } },
    header: { slots: { container: "max-w-full", title: "font-cursive" } }
  }
})
