export default defineAppConfig({
  icons: {
    alert: "line-md:bell-twotone-loop",
    areaChart: "tabler:chart-area-line",
    awards: "game-icons:money-stack",
    barChart: "solar:chart-2-bold-duotone",
    calendar: "solar:calendar-bold-duotone",
    cards: "solar:widget-bold-duotone",
    categories: "solar:sort-line-duotone",
    coach: "game-icons:teacher",
    colours: "solar:palette-round-bold-duotone",
    countries: "solar:earth-bold-duotone",
    court: "game-icons:tennis-court",
    draw: "game-icons:family-tree",
    event: "solar:calendar-mark-bold-duotone",
    filter: "line-md:filter-twotone",
    gauge: "line-md:gauge-twotone-loop",
    group: "solar:minimize-square-2-bold-duotone",
    h2h: "game-icons:crossed-swords",
    home: "line-md:home-md-twotone",
    hybrid: "solar:server-minimalistic-bold-duotone",
    layers: "solar:layers-minimalistic-line-duotone",
    lineChart: "game-icons:chart",
    list: "line-md:text-box-multiple-twotone-to-text-box-twotone-transition",
    noAwards: "tabler:cash-banknote-off",
    noCalendar: "tabler:calendar-x",
    noChart: "tabler:chart-bar-off",
    noCountries: "tabler:globe-off",
    noH2H: "tabler:sword-off",
    noPeople: "tabler:friends-off",
    noPlayer: "line-md:person-off-twotone-loop",
    noSearch: "tabler:search-off",
    noSupervisor: "line-md:clipboard-remove-twotone",
    noTournament: "tabler:trophy-off",
    one: "solar:cup-first-bold-duotone",
    overview: "tabler:list-details",
    person: "solar:user-rounded-bold-duotone",
    people: "solar:users-group-two-rounded-bold-duotone",
    player: "map:stadium",
    polarChart: "solar:round-graph-line-duotone",
    profile: "solar:user-id-bold-duotone",
    scatterChart: "tabler:chart-scatter",
    scores: "tabler:scoreboard",
    seeds: "solar:ranking-line-duotone",
    settings: "line-md:cog-loop",
    sortAlpha: "tabler:sort-a-z",
    sortAlphaDown: "tabler:sort-descending-letters",
    sortAlphaUp: "tabler:sort-ascending-letters",
    sortNumber: "tabler:sort-0-9",
    sortNumberDown: "tabler:sort-descending-numbers",
    sortNumberUp: "tabler:sort-ascending-numbers",
    stats: "solar:graph-up-bold-duotone",
    supervisor: "solar:clipboard-bold-duotone",
    table: "tabler:table",
    toc: "line-md:list-indented",
    tournament: "game-icons:trophy",
    umpire: "game-icons:whistle",
    ungroup: "solar:maximize-square-2-bold-duotone",
    upcoming: "game-icons:tennis-racket",
    venue: "tabler:building-stadium",
    year: "solar:calendar-search-bold-duotone"
  },
  colours: {
    emerald300: "#6ee7b7",
    violet700: "#6d28d9",
    teal300: "#5eead4",
    fuchsia300: "#f0abfc",
    sky700: "#0284c7",
    orange300: "#fdba74",
    rose700: "#be123c",
    lime300: "#bef264",
    cyan600: "#0891b2",
    red300: "#fca5a5",
    yellow300: "#fde047",
    green600: "#16a34a",
    blue700: "#1d4ed8",
    indigo300: "#a5b4fc",
    amber600: "#d97706",
    purple600: "#9333ea",
    pink300: "#f9a8d4",
    darkText: "#cbd5e1",
    lightText: "#475569",
    emerald700: "#047857",
    violet300: "#c4b5fd",
    fuchsia600: "#c026d3",
    sky300: "#7dd3fc",
    orange600: "#f97316",
    blue300: "#93c5fd",
    rose300: "#fda4af",
    lime500: "#84cc16",
    cyan300: "#67e8f9",
    red700: "#b91c1c",
    yellow600: "#ca8a04",
    teal700: "#0f766e",
    amber300: "#fcd34d",
    indigo700: "#4338ca",
    green300: "#86efac",
    purple300: "#d8b4fe",
    pink600: "#db2777"
  },
  ui: {
    colors: {
      primary: "violet",
      atp: "sky",
      wta: "fuchsia",
      men: "cyan",
      women: "pink",
      active: "emerald",
      inactive: "zinc",
      singles: "orange",
      doubles: "indigo",
      success: "green",
      warning: "yellow",
      error: "red",
      info: "blue",
      tour: "teal",
      challenger: "stone",
      itf: "rose",
      main: "lime",
      qualifying: "gray"
    },
    icons: {
      arrowLeft: "line-md:arrow-left-circle-twotone",
      arrowRight: "line-md:arrow-right-circle-twotone",
      caution: "line-md:alert-circle-twotone-loop",
      check: "line-md:square-twotone-to-confirm-square-twotone-transition",
      chevronDoubleLeft: "line-md:chevron-small-double-left",
      chevronDoubleRight: "line-md:chevron-small-double-right",
      chevronDown: "line-md:chevron-small-down",
      chevronLeft: "line-md:chevron-small-left",
      chevronRight: "line-md:chevron-small-right",
      chevronUp: "line-md:chevron-small-up",
      close: "line-md:close-circle-twotone",
      copy: "solar:copy-bold-duotone",
      copyCheck: "tabler:copy-check",
      dark: "line-md:moon-rising-twotone-alt-loop",
      ellipsis: "tabler:dots-circle-horizontal",
      error: "line-md:close-circle-twotone",
      external: "line-md:external-link-rounded",
      eye: "line-md:watch-twotone",
      eyeOff: "line-md:watch-off-twotone",
      file: "line-md:file-document-twotone",
      folder: "tabler:folder",
      folderOpen: "tabler:folder-open",
      hash: "line-md:hash-small",
      info: "solar:info-circle-bold-duotone",
      light: "line-md:sun-rising-twotone-loop",
      loading: "line-md:loading-twotone-loop",
      menu: "solar:hamburger-menu-line-duotone",
      minus: "line-md:minus",
      panelClose: "tabler:layout-sidebar-left-collapse",
      panelOpen: "tabler:layout-sidebar-left-expand",
      plus: "line-md:plus",
      search: "line-md:search-twotone",
      success: "line-md:circle-to-confirm-circle-twotone-transition",
      system: "line-md:monitor-twotone",
      tip: "line-md:lightbulb-twotone",
      warning: "line-md:alert-twotone-loop"
    },
    dashboardSidebar: { slots: { header: "justify-center font-cursive lg:text-lg xl:text-xl 2xl:text-2xl" } },
    dashboardPanel: {
      slots: {
        root: "h-screen max-w-screen lg:max-w-[calc(100vw-3rem)] xl:max-w-[calc(100vw-4rem)]",
        body: "scroll-smooth"
      }
    },
    dashboardToolbar: { slots: { root: "py-2 flex-wrap gap-x-4 xl:gap-x-2" } },
    table: {
      slots: {
        root: "scrollbar-thin scrollbar-thumb-primary-600 scrollbar-track-transparent",
        th: "text-xs md:text-sm text-center py-1",
        td: "text-xs md:text-sm text-center py-1"
      },
      defaultVariants: { loadingAnimation: "swing" }
    },
    badge: { defaultVariants: { variant: "outline" } },
    select: {
      slots: {
        base: "cursor-pointer w-full",
        content: "ring-primary cursor-pointer w-full",
        trailingIcon: "group-data-[state=open]:rotate-180 transition-transform duration-250"
      },
      defaultVariants: { variant: "none" }
    },
    selectMenu: {
      slots: {
        base: "cursor-pointer w-full",
        content: "ring-primary cursor-pointer lg:w-full",
        trailingIcon: "group-data-[state=open]:rotate-180 transition-transform duration-250"
      },
      defaultVariants: { variant: "none" }
    },
    dropdownMenu: {
      slots: { content: "max-h-80 !min-w-fit border border-primary", item: "cursor-pointer" }
    },
    button: {
      slots: { base: "cursor-pointer" },
      defaultVariants: { variant: "subtle" }
    },
    radioGroup: {
      slots: {
        indicator: "cursor-pointer",
        item: "cursor-pointer",
        label: "cursor-pointer"
      }
    },
    tabs: { slots: { trigger: "cursor-pointer" } },
    progress: { slots: { status: "!w-full" } }
  }
})
