export const MATCH_STATS = [
  { key: ["aces"], label: "Aces", category: "Service Stats" },
  { key: ["dfs"], label: "Double faults", category: "Service Stats", low: true },
  { label: "First serve", percent: true, category: "Service Stats" },
  { key: ["serve1_w", "serve1"], label: "1st serve points won", percent: true, category: "Service Stats" },
  { key: ["serve2_w", "serve2"], label: "2nd serve points won", percent: true, category: "Service Stats" },
  { key: ["bps_saved", "bps_faced"], label: "Break points saved", percent: true, category: "Service Stats" },
  { key: ["serve_games"], label: "Service games", percent: true, category: "Service Stats" },
  { key: ["ret1_w", "ret1"], label: "1st serve return points won", percent: true, category: "Return Stats" },
  { key: ["ret2_w", "ret2"], label: "2nd serve return points won", percent: true, category: "Return Stats" },
  { key: ["bps_converted", "bp_opps"], label: "Break points converted", percent: true, category: "Return Stats" },
  { key: ["return_games"], label: "Return games", percent: true, category: "Return Stats" },
  { key: ["winners"], label: "Winners", category: "Points Stats" },
  { key: ["ues"], label: "Unforced errors", category: "Points Stats", low: true },
  { key: ["net_w", "net"], label: "Net points won", percent: true, category: "Points Stats" },
  { label: "Service points won", percent: true, category: "Points Stats" },
  { label: "Return points won", percent: true, category: "Points Stats" },
  { label: "Total points won", percent: true, category: "Points Stats" },
  { key: ["max_speed"], label: "Max speed", category: "Service Speed" },
  { key: ["avg1_speed"], label: "1st serve average speed", category: "Service Speed" },
  { key: ["avg2_speed"], label: "2nd serve average speed", category: "Service Speed" }
]
