import { CountriesEnum } from "../types/enums";

export const COUNTRY_CODES: Record<CountriesEnum, string> = {
	// [CountriesEnum.BGD]: "bd",
	[CountriesEnum.BEL]: "be",
	// [CountriesEnum.BFA]: "bf",
	[CountriesEnum.BUL]: "bg",
	// [CountriesEnum.BHR]: "bh",
	[CountriesEnum.BIH]: "ba",
	// [CountriesEnum.BRB]: "bb",
	// WLF]: "wf",
	// BLM]: "bl",
	// BMU]: "bm",
	[CountriesEnum.BOL]: "bo",
	// BRN]: "bn",
	// BDI]: "bi",
	// BEN]: "bj",
	// BTN]: "bt",
	[CountriesEnum.JAM]: "jm",
	// BVT]: "bv",
	// BWA]: "bw",
	// WSM]: "ws",
	// BES]: "bq",
	[CountriesEnum.BRA]: "br",
	// BHS]: "bs",
	// JEY]: "je",
	[CountriesEnum.BLR]: "by",
	// BLZ]: "bz",
	[CountriesEnum.RUS]: "ru",
	// RWA]: "rw",
	[CountriesEnum.SRB]: "rs",
	// TLS]: "tl",
	// REU]: "re",
	// TKM]: "tm",
	// TJK]: "tj",
	[CountriesEnum.ROU]: "ro",
	// TKL]: "tk",
	// GNB]: "gw",
	// GUM]: "gu",
	// GTM]: "gt",
	// SGS]: "gs",
	[CountriesEnum.GRE]: "gr",
	// GNQ]: "gq",
	// GLP]: "gp",
	[CountriesEnum.JPN]: "jp",
	// GUY]: "gy",
	// GGY]: "gg",
	// GUF]: "gf",
	[CountriesEnum.GEO]: "ge",
	// GRN]: "gd",
	[CountriesEnum.GBR]: "gb",
	// GAB]: "ga",
	// SLV]: "sv",
	// GIN]: "gn",
	// GMB]: "gm",
	// GRL]: "gl",
	// GIB]: "gi",
	// GHA]: "gh",
	// OMN]: "om",
	[CountriesEnum.TUN]: "tn",
	[CountriesEnum.JOR]: "jo",
	[CountriesEnum.CRO]: "hr",
	// HTI]: "ht",
	[CountriesEnum.HUN]: "hu",
	[CountriesEnum.HKG]: "hk",
	// HND]: "hn",
	// HMD]: "hm",
	[CountriesEnum.VEN]: "ve",
	// PRI]: "pr",
	// PSE]: "ps",
	// PLW]: "pw",
	[CountriesEnum.POR]: "pt",
	// SJM]: "sj",
	// PRY]: "py",
	// IRQ]: "iq",
	[CountriesEnum.PAN]: "pa",
	// PYF]: "pf",
	// PNG]: "pg",
	[CountriesEnum.PER]: "pe",
	[CountriesEnum.PAK]: "pk",
	// PHL]: "ph",
	// PCN]: "pn",
	[CountriesEnum.POL]: "pl",
	// SPM]: "pm",
	// ZMB]: "zm",
	// ESH]: "eh",
	[CountriesEnum.EST]: "ee",
	[CountriesEnum.EGY]: "eg",
	[CountriesEnum.RSA]: "za",
	[CountriesEnum.ECU]: "ec",
	[CountriesEnum.ITA]: "it",
	// VNM]: "vn",
	// SLB]: "sb",
	// ETH]: "et",
	// SOM]: "so",
	// ZWE]: "zw",
	[CountriesEnum.KSA]: "sa",
	[CountriesEnum.ESP]: "es",
	// ERI]: "er",
	// MNE]: "me",
	[CountriesEnum.MDA]: "md",
	// MDG]: "mg",
	// MAF]: "mf",
	[CountriesEnum.MAR]: "ma",
	[CountriesEnum.MON]: "mc",
	[CountriesEnum.UZB]: "uz",
	// MMR]: "mm",
	// MLI]: "ml",
	// MAC]: "mo",
	// MNG]: "mn",
	// MHL]: "mh",
	// MKD]: "mk",
	// MUS]: "mu",
	// MLT]: "mt",
	// MWI]: "mw",
	// MDV]: "mv",
	// MTQ]: "mq",
	// MNP]: "mp",
	// MSR]: "ms",
	// MRT]: "mr",
	// IMN]: "im",
	// UGA]: "ug",
	// TZA]: "tz",
	// MYS]: "my",
	[CountriesEnum.MEX]: "mx",
	[CountriesEnum.ISR]: "il",
	[CountriesEnum.FRA]: "fr",
	// IOT]: "io",
	// SHN]: "sh",
	[CountriesEnum.FIN]: "fi",
	// FJI]: "fj",
	// FLK]: "fk",
	// FSM]: "fm",
	// FRO]: "fo",
	// NIC]: "ni",
	[CountriesEnum.NED]: "nl",
	[CountriesEnum.NOR]: "no",
	// NAM]: "na",
	// VUT]: "vu",
	// NCL]: "nc",
	// NER]: "ne",
	// NFK]: "nf",
	// NGA]: "ng",
	[CountriesEnum.NZL]: "nz",
	// NPL]: "np",
	// NRU]: "nr",
	// NIU]: "nu",
	// COK]: "ck",
	// XKX]: "xk",
	// CIV]: "ci",
	[CountriesEnum.SUI]: "ch",
	[CountriesEnum.COL]: "co",
	[CountriesEnum.CHN]: "cn",
	// CMR]: "cm",
	[CountriesEnum.CHI]: "cl",
	// CCK]: "cc",
	[CountriesEnum.CAN]: "ca",
	// COG]: "cg",
	// CAF]: "cf",
	// COD]: "cd",
	[CountriesEnum.CZE]: "cz",
	[CountriesEnum.CYP]: "cy",
	// CXR]: "cx",
	// CRI]: "cr",
	// CUW]: "cw",
	// CPV]: "cv",
	// CUB]: "cu",
	// SWZ]: "sz",
	// SYR]: "sy",
	// SXM]: "sx",
	// KGZ]: "kg",
	// KEN]: "ke",
	// SSD]: "ss",
	// SUR]: "sr",
	// KIR]: "ki",
	// KHM]: "kh",
	// KNA]: "kn",
	// COM]: "km",
	// STP]: "st",
	[CountriesEnum.SVK]: "sk",
	// KOR]: "kr",
	[CountriesEnum.SLO]: "si",
	// PRK]: "kp",
	// KWT]: "kw",
	// SEN]: "sn",
	// SMR]: "sm",
	// SLE]: "sl",
	// SYC]: "sc",
	[CountriesEnum.KAZ]: "kz",
	// CYM]: "ky",
	// SGP]: "sg",
	[CountriesEnum.SWE]: "se",
	// SDN]: "sd",
	[CountriesEnum.DOM]: "do",
	[CountriesEnum.DMA]: "dm",
	// DJI]: "dj",
	[CountriesEnum.DEN]: "dk",
	// VGB]: "vg",
	[CountriesEnum.GER]: "de",
	// YEM]: "ye",
	// DZA]: "dz",
	[CountriesEnum.USA]: "us",
	[CountriesEnum.URU]: "uy",
	// MYT]: "yt",
	// UMI]: "um",
	[CountriesEnum.LBN]: "lb",
	// LCA]: "lc",
	// LAO]: "la",
	// TUV]: "tv",
	// TWN]: "tw",
	// TTO]: "tt",
	[CountriesEnum.TUR]: "tr",
	// LKA]: "lk",
	// LIE]: "li",
	// LVA]: "lv",
	// TON]: "to",
	[CountriesEnum.LTU]: "lt",
	[CountriesEnum.LUX]: "lu",
	// LBR]: "lr",
	// LSO]: "ls",
	[CountriesEnum.THA]: "th",
	// ATF]: "tf",
	// TGO]: "tg",
	// TCD]: "td",
	// TCA]: "tc",
	// LBY]: "ly",
	// VAT]: "va",
	// VCT]: "vc",
	[CountriesEnum.UAE]: "ae",
	// AND]: "ad",
	// ATG]: "ag",
	// AFG]: "af",
	// AIA]: "ai",
	// VIR]: "vi",
	// ISL]: "is",
	// IRN]: "ir",
	[CountriesEnum.ARM]: "am",
	// ALB]: "al",
	// AGO]: "ao",
	// ATA]: "aq",
	// ASM]: "as",
	[CountriesEnum.ARG]: "ar",
	[CountriesEnum.AUS]: "au",
	[CountriesEnum.AUT]: "at",
	// ABW]: "aw",
	[CountriesEnum.IND]: "in",
	// ALA]: "ax",
	// AZE]: "az",
	[CountriesEnum.IRL]: "ie",
	// IDN]: "id",
	[CountriesEnum.UKR]: "ua",
	[CountriesEnum.QAT]: "qa"
	// MOZ]: "mz"
};
