# Generated by Django 5.0.4 on 2024-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_player_wct_round_player_wct_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='category',
            field=models.CharField(blank=True, choices=[('250', 'ATP 250'), ('500', 'ATP 500'), ('1000', 'ATP Masters 1000'), ('GS', 'Grand Slam'), ('F', 'Finals')], max_length=4, null=True),
        ),
    ]
