# Generated by Django 5.0.4 on 2024-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_alter_edition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='lda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
