# Generated by Django 5.0.4 on 2024-04-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_matchscore_tennis_matc_edition_03914b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchscore',
            name='tennis_matc_edition_03914b_idx',
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['edition', 'p1_no', 'p1', 'p2_no', 'p2'], name='tennis_matc_edition_dcf2f3_idx'),
        ),
    ]
