/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeFieldset: typeof import('primevue/fieldset')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    PrimeScrollTop: typeof import('primevue/scrolltop')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSelectButton: typeof import('primevue/selectbutton')['default']
    PrimeStep: typeof import('primevue/step')['default']
    PrimeStepList: typeof import('primevue/steplist')['default']
    PrimeStepPanel: typeof import('primevue/steppanel')['default']
    PrimeStepPanels: typeof import('primevue/steppanels')['default']
    PrimeStepper: typeof import('primevue/stepper')['default']
    PrimeTimeline: typeof import('primevue/timeline')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
